version: '3.8'
services:

    database:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        volumes:
            - /usr/todo_app_mongodb:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=rootuser
            - MONGO_INITDB_ROOT_PASSWORD=rootpass
        networks:
            - app-network

    jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins
      privileged: true
      ports:
        - "8080:8080"
      volumes:
        - /usr/jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      user: 0:0

    backend:
      build:
        context: ./
        dockerfile: Dockerfile

      ports:
        - "8000:8000"

      depends_on:

        - database
        - jenkins

      container_name: backend
      networks:
        - app-network


networks:
  app-network:
    driver: bridge